<a href="https://colab.research.google.com/github/kirthiksaran7777-afk/python-project/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:

file_path="/content/drive/MyDrive/Colab Notebooks/sales_data.csv"

In [3]:

import numpy as np
import pandas as pd


In [4]:
data=pd.read_csv(file_path)


In [5]:

data.head()

Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
0        1052  2023-02-03       Bob  North       5053.97             18   
1        1093  2023-04-21       Bob   West       4384.02             17   
2        1015  2023-09-21     David  South       4631.23             30   
3        1072  2023-08-24       Bob  South       2167.94             39   
4        1061  2023-03-24   Charlie   East       3750.20             13   

  Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
0        Furniture     152.75      267.22     Returning      0.09   
1        Furniture    3816.39     4209.44     Returning      0.11   
2             Food     261.56      371.40     Returning      0.20   
3         Clothing    4330.03     4467.75           New      0.02   
4      Electronics     637.37      692.71           New      0.08   

  Payment_Method Sales_Channel Region_and_Sales_Rep  
0           Cash        Online            North-Bob  
1           Cash        Retail             West-Bob  
2  Bank Transfer        Retail          South-David  
3    Credit Card        Retail            South-Bob  
4    Credit Card        Online         East-Charlie

In [31]:
import numpy as np

# Sample sales dataset: [OrderID, Quantity Sold, Unit Price]
sales_data = np.array([
    [1001, 10, 15.5],
    [1002, 5, 20.0],
    [1003, 8, 12.0],
    [1004, 15, 10.0],
    [1005, 7, 18.0],
    [1006, 12, 14.5],
    [1007, 6, 22.0],
    [1008, 9, 16.0]
])

print("Sales Dataset:\n", sales_data)


Sales Dataset:
 [[1001.    10.    15.5]
 [1002.     5.    20. ]
 [1003.     8.    12. ]
 [1004.    15.    10. ]
 [1005.     7.    18. ]
 [1006.    12.    14.5]
 [1007.     6.    22. ]
 [1008.     9.    16. ]]


In [32]:
quantity = sales_data[:, 1]
unit_price = sales_data[:, 2]

revenue = quantity * unit_price

total_sales = np.sum(revenue)
average_sales = np.mean(revenue)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)

Total Sales: 1077.0
Average Sales: 134.625


In [33]:
print("First 3 Records:\n", sales_data[:3])
print("Last 2 Records:\n", sales_data[-2:])
print("Quantities Only:\n", sales_data[:, 1])


First 3 Records:
 [[1001.    10.    15.5]
 [1002.     5.    20. ]
 [1003.     8.    12. ]]
Last 2 Records:
 [[1007.    6.   22.]
 [1008.    9.   16.]]
Quantities Only:
 [10.  5.  8. 15.  7. 12.  6.  9.]


In [34]:
mean_sales = np.mean(revenue)
median_sales = np.median(revenue)
variance_sales = np.var(revenue)
std_dev_sales = np.std(revenue)

print("Mean Revenue:", mean_sales)
print("Median Revenue:", median_sales)
print("Variance:", variance_sales)
print("Standard Deviation:", std_dev_sales)


Mean Revenue: 134.625
Median Revenue: 138.0
Variance: 632.734375
Standard Deviation: 25.154211873958605


In [35]:
revenue_broadcast = sales_data[:, 1] * sales_data[:, 2]
print("Revenue using Broadcasting:\n", revenue_broadcast)


Revenue using Broadcasting:
 [155. 100.  96. 150. 126. 174. 132. 144.]


In [37]:
# Apply 10% discount and calculate new revenue
discounted_price = unit_price * 0.9
new_revenue = quantity * discounted_price

print("New Revenue after 10% Discount:\n", new_revenue)


New Revenue after 10% Discount:
 [139.5  90.   86.4 135.  113.4 156.6 118.8 129.6]
